apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: pinger
  name: pinger
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pinger
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: pinger
    spec:
      containers:
      - args:
        - -endpoint=http://app.demo.svc.cluster.local:8080/ping
        - -listen-address=80
        - -pings-per-second=10
        command:
        - /bin/pinger
        image: anaisurlichs/ping-pong:latest
        imagePullPolicy: Always
        name: pinger
        ports:
        - containerPort: 80
          name: m-http
        resources: {}
status: {}
