FROM scratch
COPY --from=anaisurlichs/ping-pong:latest /bin/app /bin/app
COPY --from=anaisurlichs/ping-pong:latest /bin/pinger /bin/pinger

CMD ["/bin/app", "-set-version=best", "-latency=90%0ms,10%200ms", "-success-prob=97"]